
var HeaderDefine_COMMON = {
	RUN_BRIEFING : 100,
  CHECKALIVE :63,
    C_WEB_CLIENT_LOGIN:10,
		C_WEB_CLIENT_CONNECTED:11,
		C_WEB_CLIENT_RECONNECTED:12,
		C_WEB_CLIENT_CHECKCONNTION:13,
		C_ISLOCAL :25,
		C_WEB_CLIENT_CONNECTED_COMPLETE:23,
		C_WEB_CLIENT_CLOSE:24,
		//C_WEB_CLIENT_CONNECTED_COMPLETE_FORECAST:25,
		R_DATA:21,
		R_DATA_COMMON:22,
		
		CH_ACTGRP_ALL_STOP:45,
		CH_ACTGRP_ACT_STOP:46,
		
		CH_AUTOMANUAL:31,
		CH_ANAL_OPEN : 32,
		CH_ONOFF:33,
		CH_LAYER_SUB_STOP:36,
		CH_OPPFIT:34,
		CH_ONOFF_SUB_ALL:57,
		CH_SINGLE_VALUE:34,
		CH_MULTY_VALUE:35,
		CH_DYNAMIC_VALUE:37,
		CH_WINDDIR:38,
		CH_LIMIT_VALUE:39,
		CH_CONDITION_VALUE:40,
		CH_CONDITION_PRIORITY:41,
		CH_OPENRATE: 42,
		CH_OPENRATE_RESET:43,
		CH_RUNSTD:44,
		CH_LED:47,
		
		CH_PERIORD:51,
		CH_PRIORITY_DETAIL:52,
		CH_CUR_RULE:54,
		CH_RULE_INTERVAL:55,

		INS_PERIORD: 58,
		DEL_PERIORD: 59,
		UP_CORECTION:64,
		UP_ETC:65,
		UP_ROLL:66,
		
		
		
		WARNING:99,
		TEMPH:1,
		TEMPL:2,
		
		NOTICE:40,
		NOTICE_VALUE:53,
		
		CH_SENSOR_ALERT:61,
		CH_SENSOR_ALERT_WS:62,
		CH_REMOTE:56
		
		
};

var HeaderDefine_GREENHOUSE = {
		CONTROL_WS:41,
		CONTROL_WS_START_TEMP:1,
		CONTROL_WS_STOP_TEMP:2,
		
		CONTROL_LIGHT:51,
		CONTROL_WATER:61
		
};

var HD_HYDROPONIC = {
		//CONTROL_MIX:90,
		//CONTROL_MIX_BASIC_PH:91,
		//CONTROL_MIX_BASIC_EC:92,
		//CONTROL_MIX_RUN_SEC:93,
		//CONTROL_MIX_STANDBY_SEC:94,
		
		CONTROL_HUM:80,
		//CONTROL_HUM_BASIC_H:81,
		//CONTROL_HUM_BASIC_L:82,
		
		CONTROL_TEMP:70,
		//CONTROL_TEMP_BASIC_H:71,
		//CONTROL_TEMP_BASIC_L:72,
		
		CONTROL_PH:60,
		//CONTROL_PH_BASIC:61,
		
		CONTROL_EC:50,
		//CONTROL_EC_BASIC:51,
		
		CONTROL_LIGHT:40,
		//CONTROL_LIGHT_BASIC_S:41,
		//CONTROL_LIGHT_BASIC_E:42,
		
		CONTROL_SUPPLY:30,
		//CONTROL_SUPPLY_BASIC_R:31,
		//CONTROL_SUPPLY_BASIC_S:32,
		
		CONTROL_CO2:20,
		//CONTROL_CO2_BASIC_H:21,
		//CONTROL_CO2_BASIC_L:22
		
		
	
};